services:
  db:
    image: postgres:latest
    container_name: devbook_db
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devbook
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/18/data

volumes:
  db_data:
