services:
  - type: web
    name: devbook
    env: docker
    plan: free
    repo: https://github.com/rodriggocode/devbook-api
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    startCommand: "migrate -path /migrations -database $DATABASE_URL up && ./main"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: psql
          name: devbook
          property: connectionString

databases:
  - name: devbook
    plan: free
